// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kpkmigdujhcakknxewak.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtwa21pZ2R1amhjYWtrbnhld2FrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1ODExMTUsImV4cCI6MjA3MDE1NzExNX0.Mg-4GkYxlBycDzPehigbgUHk0HaM_82PVLLFGElu7_k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});